### ISSUE TITLE
Abstract with colored background

### ISSUE THREAD

**Issue by igel-kun** [pci-dev/latex-packages#1]
Hi, I would like to submit to a PCI, following the submission style provided here, but after working on my abstract for 15 minutes, I see yellow rectangles everywhere. Is it really a good idea to force a blue background onto the abstract? Is there any way to dispute this choice?

**Comment by tguille** [comment]
Hi igel-kun
Ok, not a good idea this blue colour. We're going to change that. In the meantime, remove the blue color of your template, it will be fine for submission. 
Best
Thomas

**Comment by igel-kun** [comment]
Thanks Thomas, it's much appreciated ;)
